version: '3.9'
services:
  ferc_scraper:
    build: .
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: python main.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_FILE=data/dockets_input.xlsx
      - OUTPUT_FILE=data/results_output.xlsx
